### ISSUE TITLE
Logbook has been updated with Addendum for paper-based materials

### ISSUE THREAD

**Issue by rtroncy** [silknow/crawler#29]
The [Logbook for Harvesting Data from Museums](https://docs.google.com/document/d/1Tg4gDlz8HjILPRQ8XBOBFo-3-74nmJdJ31YL6PUtdB4/edit#) has been updated along the time. 

@ehrhart There is a need to review the museum sources which have been crawled already as the search strategies have been enhanced. Pay attention, in particular, to the Addendum added for a large number of sources.

**Comment by rtroncy** [comment]
The addendum is particularly relevant for some museums, such as CERES, see https://docs.google.com/document/d/1Tg4gDlz8HjILPRQ8XBOBFo-3-74nmJdJ31YL6PUtdB4/edit#heading=h.sfeb7xefe1rk as well as [this email](https://lists.eurecom.fr/sympa/arc/silknow/2020-09/msg00045.html) and [this email](https://lists.eurecom.fr/sympa/arc/silknow/2020-09/msg00048.html).

**Comment by ehrhart** [comment]
@tschleider 

### CERES Museum has been updated

Records: [ceres-mcu_records_20210503_4.tar.gz](https://silknow.uv.es/owncloud/index.php/f/704205)
Images: [ceres-mcu_files_20210503_4.tar.gz](https://silknow.uv.es/owncloud/index.php/f/704230)

_Note: the fields that come from [museosdeandalucia](http://www.museosdeandalucia.es/web/museosdeandalucia/fondos-museisticos) are slightly different than the others, since it's a different website layout and data structure. Please refer to the [updated list of known fields](https://github.com/silknow/crawler/wiki/List-of-known-fields#red-digital-de-colecciones-de-museos-de-espa%C3%B1a) for some examples._

### ARTIC Museum has been updated

Records: [artic_records_20210503_2.tar.gz](https://silknow.uv.es/owncloud/index.php/f/704232)
Images: [artic_files_20210503_2.tar.gz](https://silknow.uv.es/owncloud/index.php/f/704285)

**Comment by rtroncy** [comment]
@ehrhart Can this issue be closed? What is left to do?

**Comment by ehrhart** [comment]
This issue can indeed be closed since all the changes have been implemented.
